biblioteca/applications/editorial/urls.py
from django.urls import path
from . import views

app_name = 'editorial_app'

urlpatterns = [
    path(
        'editorial/inicio', 
        views.EditorialInicioTemplateView.as_view(), 
        name='inicio'
        ),
    path(
        'editorial/lista', 
        views.ListAllEditoriales.as_view(), 
        name='listar'
        ),
    path(
        'editorial/detalles/<pk>/', 
        views.EditorialDetailView.as_view(),
        name='detalles'
        ),
    path(
        'editorial/add',
        views.EditorialCreateView.as_view(), 
        name='add'
        ),
    path(
        'editorial/edit/<pk>/', 
        views.EditorialUpdateView.as_view(), 
        name='edit'
        ),
    path(
        'editorial/delete/<pk>/', 
        views.EditorialDeleteView.as_view(), 
        name='delete'
        )
]

biblioteca/biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.libro.urls')),
    path('', include('applications.autor.urls')),
    path('', include('applications.ubicacion.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.genero.urls')),
    path('', include('applications.editorial.urls'))
]

biblioteca/applications/editorial/models.py
from django.db import models


class Editorial(models.Model):

    nombre = models.CharField('Editorial', max_length=32, unique=True)
    pais = models.CharField('País', max_length=16, blank=True, help_text='País de Origen')
    web = models.URLField('Página Web', max_length=256, blank=True)


    class Meta:
        verbose_name = 'Editorial'
        verbose_name_plural = 'Editoriales'
        ordering = ['nombre']


    def __str__(self):
        return f'{self.nombre}'

biblioteca/applications/editorial/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from .models import Editorial


# Inicio para la Ubicación :: inicio
class EditorialInicioTemplateView(TemplateView):
    template_name = 'editorial/inicio.html'


# Listar todas la Editoriales :: listar
class ListAllEditoriales(ListView):
    template_name = 'editorial/listar_editoriales.html'
    paginate_by = 12
    ordering = 'nombre'
    context_object_name = 'editorial'

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        
        lista = Editorial.objects.filter(
            nombre__icontains=palabra_clave
        )
        return lista


# Ver la información del editorial :: detalles
class EditorialDetailView(DetailView):
    model = Editorial
    template_name = 'editorial/ver_editorial.html'


# Añadir un nueva editorial :: add
class EditorialCreateView(CreateView):
    template_name = "editorial/add_editorial.html"
    model = Editorial
    fields = ('__all__')
    success_url = reverse_lazy('editorial_app:listar')

    # def form_valid(self, form):      
    #     return super().form_valid(form)


# Modificar el editorial :: edit
class EditorialUpdateView(UpdateView):
    template_name = 'editorial/edit_editorial.html'
    model = Editorial
    fields = ('__all__')
    success_url = reverse_lazy('editorial_app:listar')


# Eliminar editorial :: delete
class EditorialDeleteView(DeleteView):
    template_name = 'editorial/delete_editorial.html'
    model = Editorial
    fields = ('__all__')
    success_url = reverse_lazy('editorial_app:listar')

biblioteca/templates/editorial/add_editorial.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - Añadir Editorial {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x align-center" style="padding-bottom: 25px;">
        <div class="cell large-12">
            <h2 style="text-align: center;">Añadir <b>Editorial</b></h2>
        </div>
    </div>

    <div class="grid-x align-center align-middle">
        <form class="cell large-6" action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <p style="text-align:right; padding-top: 25px;">
                <button class="button primary align-rigth" type="submit">Añadir</button>
            </p>
        </form>
    </div> 

</div>
{% endblock content %}

biblioteca/templates/editorial/delete_editorial.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - Eliminar {{ editorial.nombre }} {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x align-center" style="padding-bottom: 25px;">
        <div class="cell large-12">
            <h2 style="text-align: center;">Eliminar <b>{{ editorial.nombre }}</b></h2>
        </div>
    </div>

    <div class="grid-x align-center align-middle">
        <form class="cell large-8" method="POST">{% csrf_token %}
            <div class="callout alert" style="text-align: center;">
                <p>¿Desea eliminar la editorial <b>{{ editorial.nombre }}</b>?</p>
                <button class="button alert" type="submit">Confirmar</button>
            </div>
        </form>
    </div>

    <div class="grid-x align-center">
        <div class="cell large-1">
            <input type="button" class="button secondary clear" onclick="history.back()" name="Volver" value="Volver">
        </div>
    </div>

</div>
{% endblock content %}

biblioteca/templates/editorial/edit_editorial.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - Editar {{editorial.nombre}} {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x align-center" style="padding-bottom: 25px;">
        <div class="cell large-12">
            <h2 style="text-align: center;">Modificar <b>{{ editorial.nombre }}</b></h2>
        </div>
    </div>

    <div class="grid-x align-center align-middle">
        <form class="cell large-6" action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <p style="text-align:right; padding-top: 25px;">
                <button class="button primary align-rigth" type="submit">Actualizar</button>
                <button class="button secondary align-center" lass="button secondary clear" onclick="history.back()">Volver</button>
            </p>

        </form>
    </div>

</div>
{% endblock content %}

biblioteca/templates/editorial/inicio.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - Pag. Editorial {% endblock title %}
{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-x align-center">
        <div class="cell large-12">
            <h2 style="text-align: center;"><b>E D I T O R I A L<b></h2>
        </div>
    </div>
    <div class="grid-x align-center">
        <div class="cell large-12" style="padding-bottom:25px;">
            <h5 style="text-align: center; font-style: italic;">Página inicial para gestionar las <i>editoriales</i></h5>
        </div>

        <div class="cell grid-x large-12 grid-padding-x align-center">
            <div class="cell grid-x large-6 align-center align-middle">
                <div class="cell large-12">
                    <div class="callout success" style="text-align: center;">
                        <p>Da de alta las nuevas editoriales en <i>MyBiblio</i></p>
                        <a class="button success" href="{% url 'editorial_app:add' %}">Añadir</a>
                      </div>
                </div>

                <div class="cell large-12">
                    <div class="callout primary" style="text-align: center;">
                        <p>Gestiona tus editoriales: Consulta, Modifica y Borra</p>
                        <a class="button primary" href="{% url 'editorial_app:listar' %}">Gestionar</a>
                      </div>
                </div>     
            </div>
            <div class="cell grid-x large-6 align-middle align-center">
                <img class="max-width: 400px; height: auto;" src="{% static 'img/editorial_main.jpg' %}">
            </div>
        </div>
    </div>
{% endblock content %}

biblioteca/templates/editorial/listar_editoriales.html
{% extends 'base.html' %}
{% block title %}MyBiblio - Lista de editoriales{% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x align-center" style="padding-bottom: 25px;">
        <div class="cell large-12">
            <h2 style="text-align: center;">Lista de <b>editoriales</b></h2>
        </div>
    </div>


    <div class="grid-x">
        <form method="GET" class="cell grid-x grid-margin-x">{% csrf_token %}
            <div class="cell large-4">
                <input type="text" placeholder="Buscar Editorial">
            </div>
            <div class="cell large-2">
                <button type="submit" id="kword" name="kword" class="primay button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200" style="text-align: center;">Editorial</th>
                        <th width="200" style="text-align: center;">País</th>
                        <th width="200" style="text-align: center;">Pag. Web</th>
                        <th width="100" style="text-align: center;">Acción</th>

                    </tr>
                </thead>
                <tbody style=" font-size: 12px;">
                    {% for e in editorial %}
                    <tr>
                        <td>{{ e.nombre }}</td>
                        <td style="text-align: center;">
                            {{ e.pais }}
                        </td>
                        <td style="text-align: center;">{{ e.web }}</td>
                        <td style="text-align: center;">
                            <a class="button success tiny" href="{% url 'editorial_app:detalles' e.id %}">V</a>
                            <a class="button warning tiny" href="{% url 'editorial_app:edit' e.id %}">M</a>
                            <a class="button alert tiny" href="{% url 'editorial_app:delete' e.id %}">E</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">
                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{ page_obj.previous_page_number }}" aria-label="Anterior">
                                Anterior
                            </a>
                        </li>
                    {% endif %}

                    {% for pag in paginator.page_range %}
                        
                        {% if pag == page_obj.number %}
                            <li class="current">
                                <span class="show-for-sr">Estás en la pag.</span>{{ pag }}
                            </li>
                        {% else %}
                            <li>
                                <a href="?page={{ pag }}" aria-label="Pag. {{ pag }}">{{ pag }}</a>
                            </li>                            
                        {% endif %}

                    {% endfor%}

                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}" aria-label="Siguiente">
                                Siguiente
                            </a>
                        </li>
                    {% endif %}

                </ul>
            </nav>
            {% endif %}
        </div>
    </div>


</div>

{% endblock content %}

biblioteca/templates/editorial/ver_editorial.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - Editorial "{{ editorial.nombre }}"{% endblock title %}
{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x align-center" style="padding-bottom: 25px;">
            <div class="cell large-12">
                <h2 style="text-align: center;">{{ editorial.nombre }}</h2>
            </div>
        </div>

        <div class="grid-x align-center">
            <!-- <div class="cell large-4 large-offset-2">
                <img class="max-width: 350px; height: auto;" src="{% static 'img/book-no-cover.png' %}">
            </div> -->
            <div class="grid-x cell large-6 grid-margin-x align-top">
                <div class="cell large-4" style="text-align: right; font-weight:bolder;">
                    Editorial:
                </div>
                <div class="cell large-8 textocamposrigth">
                    {{ editorial.nombre}}
                </div>

                <div class="cell large-4" style="text-align: right; font-weight:bolder;">
                    País: 
                </div>
                <div class="cell large-8">
                    {{ editorial.pais }}
                </div>

                <div class="cell large-4" style="text-align: right; font-weight:bolder;">
                    Pag. Web: 
                </div>
                <div class="cell large-8">
                    {{ editorial.web}}
                </div>
            </div>
        </div>

        <div class="grid-x align-center">
            <div class="cell large-1">
                <p style="text-align:right; padding-top: 25px;">
                    <button class="button secondary align-center" lass="button secondary clear" onclick="history.back()">Volver</button>
                </p>
            </div>
        </div>

    </div>
{% endblock content %}