biblioteca/applications/autor/urls.py
from django.urls import path
from . import views

app_name = 'autor_app'

urlpatterns = [
    path(
        'autor/inicio', 
        views.AutorInicioTemplateView.as_view(), 
        name='inicio'
        ),
    path(
        'autor/lista',
        views.ListAllAutores.as_view(), 
        name='listar'
        ),
    path(
        'autor/detalles/<pk>/', 
        views.AutorDetailView.as_view(),
        name='detalles'
        ),
    path(
        'autor/add',
        views.AutorCreateView.as_view(), 
        name='add'
        ),
    path(
        'autor/edit/<pk>/', 
        views.AutorUpdateView.as_view(), 
        name='edit'
        ),
    path(
        'autor/delete/<pk>/', 
        views.AutorDeleteView.as_view(), 
        name='delete'
        )
]

biblioteca/applications/genero/urls.py
from django.urls import path
from . import views

app_name = 'genero_app'

urlpatterns = [
    path(
        'genero/inicio', 
        views.GeneroInicioTemplateView.as_view(), 
        name='inicio'
        ),
    path(
        'genero/lista', 
        views.ListAllGeneros.as_view(), 
        name='listar'
        ),
    path(
        'genero/detalles/<pk>/', 
        views.GeneroDetailView.as_view(),
        name='detalles'
        ),
    path(
        'genero/add',
        views.GeneroCreateView.as_view(), 
        name='add'
        ),
    path(
        'genero/edit/<pk>/', 
        views.GeneroUpdateView.as_view(), 
        name='edit'
        ),
    path(
        'genero/delete/<pk>/', 
        views.GeneroDeleteView.as_view(), 
        name='delete'
        )
]

biblioteca/applications/home/urls.py
from django.urls import path
from . import views

app_name = 'home_app'

urlpatterns = [path(
    '', 
    views.InicioView.as_view(),
    name='inicio'
    )

]

biblioteca/applications/libro/urls.py
from django.urls import path
from . import views

app_name = 'libro_app'

urlpatterns = [
    path(
        'libro/inicio', 
        views.LibroInicioTemplateView.as_view(), 
        name='inicio'
        ),
    path(
        'libro/lista', 
        views.ListAllLibros.as_view(), 
        name='listar'
        ),
    path(
        'libro/detalles/<pk>/', 
        views.LibroDetailView.as_view(),
        name='detalles'
        ),
    path(
        'libro/add',
        views.LibroCreateView.as_view(), 
        name='add'
        ),
    path(
        'libro/edit/<pk>/', 
        views.LibroUpdateView.as_view(), 
        name='edit'
        ),
    path(
        'libro/delete/<pk>/', 
        views.LibroDeleteView.as_view(), 
        name='delete'
        )
]

biblioteca/biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.libro.urls')),
    path('', include('applications.autor.urls')),
    path('', include('applications.ubicacion.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.genero.urls')),
    path('', include('applications.editorial.urls'))
]

biblioteca/templates/includes/base_esqueleto.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - XXXXXXXXXXXXXX {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x align-center" style="padding-bottom: 25px;">
        <div class="cell large-12">
            <h2 style="text-align: center;">Lista de <b>libros</b></h2>
        </div>
    </div>


    <div class="grid-x">
        <div class="cell"
    </div> 

</div>

{% endblock content %}

biblioteca/templates/includes/header.html
{% load static %}
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
    <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="responsive-menu">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text">MyBiblio</li>
            <li><a href="{% url 'home_app:inicio' %}">Inicio</a></li>
            <li><a href="{% url 'libro_app:inicio' %}">Libros</a></li>
            <li><a href="{% url 'autor_app:inicio' %}">Autores</a></li>
            <li><a href="{% url 'genero_app:inicio' %}">Géneros</a></li>
            <li><a href="{% url 'ubicacion_app:inicio' %}">Ubicaciones</a></li>
            <li><a href="{% url 'editorial_app:inicio' %}">Editoriales</a></li>
            <li class="has-submenu">
                <a href="#0">Listar</a>
                <ul class="submenu menu vertical" data-submenu>
                    <li><a href="{% url 'libro_app:listar' %}">Libros</a></li>
                    <li><a href="{% url 'autor_app:listar' %}">Autores</a></li>
                    <li><a href="{% url 'genero_app:listar' %}">Géneros</a></li>
                    <li><a href="{% url 'ubicacion_app:listar' %}">Ubicaciones</a></li>
                    <li><a href="{% url 'editorial_app:listar' %}">Editoriales</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="top-bar-right">
    </div>
</div>
<div class="orbit" role="region" aria-label="Header images MyBiblio" data-orbit style="padding-bottom: 25px;">
    <div class="orbit-wrapper">
        <ul class="orbit-container">
            <li class="is-active orbit-slide">
                <figure class="orbit-figure">
                    <img class="orbit-image" src="{% static 'img/header-large.jpg' %}" alt="Books">
                </figure>
            </li>
        </ul>
    </div>
</div>