biblioteca/applications/libro/urls.py
from django.urls import path
from . import views

app_name = 'libro_app'

urlpatterns = [
    path(
        'libro/inicio', 
        views.LibroInicioTemplateView.as_view(), 
        name='inicio'
        ),
    path(
        'libro/lista', 
        views.ListAllLibros.as_view(), 
        name='listar'
        ),
    path(
        'libro/detalles/<pk>/', 
        views.LibroDetailView.as_view(),
        name='detalles'
        ),
    path(
        'libro/add',
        views.LibroCreateView.as_view(), 
        name='add'
        ),
    path(
        'libro/edit/<pk>/', 
        views.LibroUpdateView.as_view(), 
        name='edit'
        ),
    path(
        'libro/delete/<pk>/', 
        views.LibroDeleteView.as_view(), 
        name='delete'
        )
]

biblioteca/biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.libro.urls')),
    path('', include('applications.autor.urls')),
    path('', include('applications.ubicacion.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.genero.urls')),
    path('', include('applications.editorial.urls'))
]

biblioteca/applications/libro/models.py
from django.db import models

from applications.autor.models import Autor
from applications.editorial.models import Editorial
from applications.genero.models import Genero
from applications.ubicacion.models import Ubicacion


class Libro(models.Model):

    titulo = models.CharField(
        'Título', 
        max_length=64
        )

    autor = models.ManyToManyField(
        Autor
        )

    genero = models.ForeignKey(
        Genero,
        on_delete=models.CASCADE
        )

    editorial = models.ForeignKey(
        Editorial,
        on_delete=models.CASCADE
        )

    isbn = models.CharField(
        'ISBN', 
        max_length=16, 
        unique=True
        )

    # foto = models.ImageField(
    #     upload_to='libros',
    #     blank=True,
    #     null=True
    #     )

    ubicacion = models.ForeignKey(
        Ubicacion,
        on_delete=models.CASCADE
        )

    resumen = models.CharField(
        'Resumen', 
        max_length=1024, 
        blank=True
        )

    class Meta:
        verbose_name = 'Libro'
        verbose_name_plural = 'Libros'
        ordering = ['titulo']


    def __str__(self):
        return f'{self.titulo}'

biblioteca/applications/libro/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from .models import Libro


# Inicio para los Libros :: inicio
class LibroInicioTemplateView(TemplateView):
    template_name = 'libro/inicio.html'


# Listar todos los libros :: listar
class ListAllLibros(ListView):
    template_name = 'libro/listar_libros.html'
    # model = Libro
    paginate_by = 12
    ordering = 'titulo'
    context_object_name = 'libros'

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        
        lista = Libro.objects.filter(
            titulo__icontains=palabra_clave
        )
        return lista


# Ver la información del libro :: detalles
class LibroDetailView(DetailView):
    model = Libro
    template_name = 'libro/ver_libro.html'


# Añadir un nuevo libro :: add
class LibroCreateView(CreateView):
    template_name = "libro/add_libro.html"
    model = Libro
    fields = ('__all__')
    success_url = reverse_lazy('libro_app:listar')

    # def form_valid(self, form):      
    #     return super().form_valid(form)


# Modificar el libro :: edit
class LibroUpdateView(UpdateView):
    template_name = 'libro/edit_libro.html'
    model = Libro
    fields = ('__all__')
    success_url = reverse_lazy('libro_app:listar')


# Eliminar libro :: delete
class LibroDeleteView(DeleteView):
    template_name = 'libro/delete_libro.html'
    model = Libro
    fields = ('__all__')
    success_url = reverse_lazy('libro_app:listar')

biblioteca/templates/libro/add_libro.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - Añadir Libro {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x align-center" style="padding-bottom: 25px;">
        <div class="cell large-12">
            <h2 style="text-align: center;">Añadir <b>Libro</b></h2>
        </div>
    </div>

    <div class="grid-x align-center align-middle">
        <form class="cell large-6" action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <p style="text-align:right; padding-top: 25px;">
                <button class="button primary align-rigth" type="submit">Añadir</button>
            </p>
        </form>
    </div> 

</div>
{% endblock content %}

biblioteca/templates/libro/delete_libro.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - Eliminar {{ libro.titulo }} {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x align-center" style="padding-bottom: 25px;">
        <div class="cell large-12">
            <h2 style="text-align: center;">Eliminar <b>{{ libro.titulo }}</b></h2>
        </div>
    </div>

    <div class="grid-x align-center align-middle">
        <form class="cell large-8" method="POST">{% csrf_token %}
            <div class="callout alert" style="text-align: center;">
                <p>¿Desea eliminar el libro <b>{{ libro.titulo }}</b> ( ISBN: {{libro.isbn}} )?</p>
                <button class="button alert" type="submit">Confirmar</button>
            </div>
        </form>
    </div>

    <div class="grid-x align-center">
        <div class="cell large-1">
            <input type="button" class="button secondary clear" onclick="history.back()" name="Volver" value="Volver">
        </div>
    </div>

</div>
{% endblock content %}

biblioteca/templates/libro/edit_libro.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - Editar {{libro.titulo}} {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x align-center" style="padding-bottom: 25px;">
        <div class="cell large-12">
            <h2 style="text-align: center;">Modificar <b>{{ libro.titulo }}</b></h2>
        </div>
    </div>

    <div class="grid-x align-center align-middle">
        <form class="cell large-6" action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <p style="text-align:right; padding-top: 25px;">
                <button class="button primary align-rigth" type="submit">Actualizar</button>
                <button class="button secondary align-center" lass="button secondary clear" onclick="history.back()">Volver</button>
            </p>

        </form>
    </div>

</div>
{% endblock content %}

biblioteca/templates/libro/inicio.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - Pag. Libros {% endblock title %}
{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-x align-center">
        <div class="cell large-12">
            <h2 style="text-align: center;"><b>L I B R O S<b></h2>
        </div>
    </div>
    <div class="grid-x align-center">
        <div class="cell large-12" style="padding-bottom:25px;">
            <h5 style="text-align: center; font-style: italic;">Página inicial para gestionar los <i>libros</i></h5>
        </div>

        <div class="cell grid-x large-12 grid-padding-x align-center">
            <div class="cell grid-x large-6 align-center align-middle">
                <div class="cell large-12">
                    <div class="callout success" style="text-align: center;">
                        <p>Da de alta tus nuevos libros en <i>MyBiblio</i></p>
                        <a class="button success" href="{% url 'libro_app:add' %}">Añadir</a>
                      </div>
                </div>

                <div class="cell large-12">
                    <div class="callout primary" style="text-align: center;">
                        <p>Gestiona tu biblioteca: Consulta, Modifica y Borra</p>
                        <a class="button primary" href="{% url 'libro_app:listar' %}">Gestionar</a>
                      </div>
                </div>     
            </div>
            <div class="cell grid-x large-6 align-middle align-center">
                <img class="max-width: 400px; height: auto;" src="{% static 'img/libros_main.jpg' %}">
            </div>
        </div>
    </div>
{% endblock content %}

biblioteca/templates/libro/listar_libros.html
{% extends 'base.html' %}
{% block title %}MyBiblio - Lista de libros{% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x align-center" style="padding-bottom: 25px;">
        <div class="cell large-12">
            <h2 style="text-align: center;">Lista de <b>libros</b></h2>
        </div>
    </div>


    <div class="grid-x">
        <form method="GET" class="cell grid-x grid-margin-x">{% csrf_token %}
            <div class="cell large-4">
                <input type="text" placeholder="Buscar Libro">
            </div>
            <div class="cell large-2">
                <button type="submit" id="kword" name="kword" class="primay button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200" style="text-align: center;">Título</th>
                        <th width="200" style="text-align: center;">Autor</th>
                        <th width="100" style="text-align: center;">Género</th>
                        <th width="150" style="text-align: center;">Editorial</th>
                        <th width="100" style="text-align: center;">ISBN</th>
                        <th width="150" style="text-align: center;">Ubicación</th>
                        <th width="150" style="text-align: center;">Acción</th>
                    </tr>
                </thead>
                <tbody style=" font-size: 12px;">
                    {% for l in libros %}
                    <tr>
                        <td>{{ l.titulo }}</td>
                        <td>
                            <ul style="list-style: none;">
                                {% for a in l.autor.all %}
                                    <li>
                                        {{ a.nombre }} {{ a.apellidos }}
                                    </li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td style="text-align: center;">
                            <span data-tooltip tabindex="1" title="{{ l.genero.nombre }}">
                                {{ l.genero.codigo }}
                            </span>
                        </td>
                        <td style="text-align: center;">{{ l.editorial }}</td>
                        <td style="text-align: center;">{{ l.isbn }}</td>
                        <td style="text-align: center;">
                            <span data-tooltip tabindex="1" title="{{ l.ubicacion.nombre }}">
                                {{ l.ubicacion.codigo }}
                            </span>
                        </td>
                        <td style="text-align: center;">
                            <a class="button success tiny" href="{% url 'libro_app:detalles' l.id %}">V</a>
                            <a class="button warning tiny" href="{% url 'libro_app:edit' l.id %}">M</a>
                            <a class="button alert tiny" href="{% url 'libro_app:delete' l.id %}">E</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">
                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{ page_obj.previous_page_number }}" aria-label="Anterior">
                                Anterior
                            </a>
                        </li>
                    {% endif %}

                    {% for pag in paginator.page_range %}
                        
                        {% if pag == page_obj.number %}
                            <li class="current">
                                <span class="show-for-sr">Estás en la pag.</span>{{ pag }}
                            </li>
                        {% else %}
                            <li>
                                <a href="?page={{ pag }}" aria-label="Pag. {{ pag }}">{{ pag }}</a>
                            </li>                            
                        {% endif %}

                    {% endfor%}

                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}" aria-label="Siguiente">
                                Siguiente
                            </a>
                        </li>
                    {% endif %}

                </ul>
            </nav>
            {% endif %}
        </div>
    </div>


</div>

{% endblock content %}

biblioteca/templates/libro/ver_libro.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - Libro "{{ libro.titulo }} {% endblock title %}
{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x align-center" style="padding-bottom: 25px;">
            <div class="cell large-12">
                <h2 style="text-align: center;">{{ libro.titulo }}</h2>
            </div>
        </div>

        <div class="grid-x align-center">
            <div class="cell large-4 align-middle large-offset-2">
                <img class="max-width: 350px; height: auto;" src="{% static 'img/book-no-cover.png' %}">
            </div>
            <div class="grid-x cell large-6 grid-margin-x">
                <div class="cell large-4" style="text-align: right; font-weight:bolder;">
                    Titulo:
                </div>
                <div class="cell large-8 textocamposrigth">
                    {{ libro.titulo}}
                </div>

                <div class="cell large-4" style="text-align: right; font-weight:bolder;">
                    Autor: 
                </div>
                <div class="cell large-8">
                    <ul style="list-style: none; margin: 0; list-style-type: none;">
                        {% for autor  in libro.autor.all%}
                            <li>{{ autor.nombre }} {{ autor.apellidos }}</li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="cell large-4" style="text-align: right; font-weight:bolder;">
                    Editorial: 
                </div>
                <div class="cell large-8">
                    {{ libro.editorial}}
                </div>

                <div class="cell large-4" style="text-align: right; font-weight:bolder;">
                    Género: 
                </div>
                <div class="cell large-8">
                    {{ libro.genero.nombre}}
                </div>

                <div class="cell large-4" style="text-align: right; font-weight:bolder;">
                    ISBN: 
                </div>
                <div class="cell large-8">
                    {{ libro.isbn}}
                </div>

                <div class="cell large-4" style="text-align: right; font-weight:bolder;">
                    Ubicación: 
                </div>
                <div class="cell large-8">
                    {{ libro.ubicacion}}
                </div>
            </div>
        </div>

        <div class="grid-x align-center">
            <div class="cell large-1">
                <p style="text-align:right; padding-top: 25px;">
                    <button class="button secondary align-center" lass="button secondary clear" onclick="history.back()">Volver</button>
                </p>
            </div>
        </div>

    </div>
{% endblock content %}