biblioteca/applications/autor/urls.py
from django.urls import path
from . import views

app_name = 'autor_app'

urlpatterns = [
    path(
        'autor/inicio', 
        views.AutorInicioTemplateView.as_view(), 
        name='inicio'
        ),
    path(
        'autor/lista',
        views.ListAllAutores.as_view(), 
        name='listar'
        ),
    path(
        'autor/detalles/<pk>/', 
        views.AutorDetailView.as_view(),
        name='detalles'
        ),
    path(
        'autor/add',
        views.AutorCreateView.as_view(), 
        name='add'
        ),
    path(
        'autor/edit/<pk>/', 
        views.AutorUpdateView.as_view(), 
        name='edit'
        ),
    path(
        'autor/delete/<pk>/', 
        views.AutorDeleteView.as_view(), 
        name='delete'
        )
]

biblioteca/biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.libro.urls')),
    path('', include('applications.autor.urls')),
    path('', include('applications.ubicacion.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.genero.urls')),
    path('', include('applications.editorial.urls'))
]

biblioteca/applications/autor/models.py
from django.db import models

class Autor(models.Model):

    nombre = models.CharField('Nombre', max_length=32)
    apellidos = models.CharField('Apellidos', max_length=32)
    # foto = models.ImageField(upload_to='autor', blank=True, null=True)
    # nombre_completo = models.CharField('Nombre completo', max_length=64, blank=True)


    class Meta:
        verbose_name = 'Autor'
        verbose_name_plural = 'Autores'
        ordering = ['apellidos', 'nombre']


    def __str__(self):
        return f'{self.apellidos}, {self.nombre}'

biblioteca/applications/autor/forms.py
from django import forms
from .models import Autor

class AutorCreateForm(forms.ModelForm):
    
    class Meta:
        model = Autor
        fields = (
            'nombre',
            'apellidos',
        )

        widgets = {
            'nombre': forms.TextInput(
                attrs = {
                    'placeholder': 'Ingrese el nombre'
                }
            ),
            'apellidos': forms.TextInput(
                attrs = {
                    'placeholder': 'Ingrese los apellidos'
                }
            )
        }

    def clean_nombre(self):
        nombre = self.cleaned_data['nombre']
        nombre = nombre.strip()
        if len(nombre) <= 0:
            raise forms.ValidationError('Nombre en blanco')

        return nombre

biblioteca/applications/autor/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from .models import Autor


# Inicio para la Ubicación :: inicio
class AutorInicioTemplateView(TemplateView):
    template_name = 'autor/inicio.html'


# Listar todos los Autores :: listar
class ListAllAutores(ListView):
    template_name = 'autor/listar_autores.html'
    paginate_by = 12
    ordering = 'nombre'
    context_object_name = 'autor'

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        
        lista = Autor.objects.filter(
            nombre__icontains=palabra_clave
        )
        return lista


# Ver la información del autor :: detalles
class AutorDetailView(DetailView):
    model = Autor
    template_name = 'autor/ver_autor.html'


# Añadir un nuevo autor :: add
class AutorCreateView(CreateView):
    template_name = "autor/add_autor.html"
    model = Autor
    fields = ('__all__')
    success_url = reverse_lazy('autor_app:listar')

    # def form_valid(self, form):      
    #     return super().form_valid(form)


# Modificar el autor :: edit
class AutorUpdateView(UpdateView):
    template_name = 'autor/edit_autor.html'
    model = Autor
    fields = ('__all__')
    success_url = reverse_lazy('autor_app:listar')


# Eliminar autor :: delete
class AutorDeleteView(DeleteView):
    template_name = 'autor/delete_autor.html'
    model = Autor
    fields = ('__all__')
    success_url = reverse_lazy('autor_app:listar')

biblioteca/templates/autor/add_autor.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - Añadir Autor {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x align-center" style="padding-bottom: 25px;">
        <div class="cell large-12">
            <h2 style="text-align: center;">Añadir <b>Autor</b></h2>
        </div>
    </div>

    <div class="grid-x align-center align-middle">
        <form class="cell large-6" action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <p style="text-align:right; padding-top: 25px;">
                <button class="button primary align-rigth" type="submit">Añadir</button>
            </p>
        </form>
    </div> 

</div>
{% endblock content %}

biblioteca/templates/autor/delete_autor.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - Eliminar {{ autor.nombre }} {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x align-center" style="padding-bottom: 25px;">
        <div class="cell large-12">
            <h2 style="text-align: center;">Eliminar <b>{{ autor.nombre }}</b></h2>
        </div>
    </div>

    <div class="grid-x align-center align-middle">
        <form class="cell large-8" method="POST">{% csrf_token %}
            <div class="callout alert" style="text-align: center;">
                <p>¿Desea eliminar el autor <b>{{ autor.nombre }}</b>?</p>
                <button class="button alert" type="submit">Confirmar</button>
            </div>
        </form>
    </div>

    <div class="grid-x align-center">
        <div class="cell large-1">
            <input type="button" class="button secondary clear" onclick="history.back()" name="Volver" value="Volver">
        </div>
    </div>

</div>
{% endblock content %}

biblioteca/templates/autor/edit_autor.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - Editar el autor "{{ autor.nombre }} {{ autor.apellidos }}" {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x align-center" style="padding-bottom: 25px;">
        <div class="cell large-12">
            <h2 style="text-align: center;">Modificar el autor "<b>{{ autor.nombre }} {{ autor.apellidos }}</b">"</h2>
        </div>
    </div>

    <div class="grid-x align-center align-middle">
        <form class="cell large-6" action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <p style="text-align:right; padding-top: 25px;">
                <button class="button primary align-rigth" type="submit">Actualizar</button>
                <button class="button secondary align-center" lass="button secondary clear" onclick="history.back()">Volver</button>
            </p>

        </form>
    </div>

</div>
{% endblock content %}

biblioteca/templates/autor/inicio.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - Pag. Autor {% endblock title %}
{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-x align-center">
        <div class="cell large-12">
            <h2 style="text-align: center;"><b>A U T O R<b></h2>
        </div>
    </div>
    <div class="grid-x align-center">
        <div class="cell large-12" style="padding-bottom:25px;">
            <h5 style="text-align: center; font-style: italic;">Página inicial para gestionar los <i>autores</i></h5>
        </div>

        <div class="cell grid-x large-12 grid-padding-x align-center">
            <div class="cell grid-x large-6 align-center align-middle">
                <div class="cell large-12">
                    <div class="callout success" style="text-align: center;">
                        <p>Da de alta las nuevas autores en <i>MyBiblio</i></p>
                        <a class="button success" href="{% url 'autor_app:add' %}">Añadir</a>
                      </div>
                </div>

                <div class="cell large-12">
                    <div class="callout primary" style="text-align: center;">
                        <p>Gestiona los autores: Consulta, Modifica y Borra</p>
                        <a class="button primary" href="{% url 'autor_app:listar' %}">Gestionar</a>
                      </div>
                </div>     
            </div>
            <div class="cell grid-x large-6 align-middle align-center">
                <img class="max-width: 400px; height: auto;" src="{% static 'img/editorial_main.jpg' %}">
            </div>
        </div>
    </div>
{% endblock content %}

biblioteca/templates/autor/listar_autores.html
{% extends 'base.html' %}
{% block title %}MyBiblio - Lista de autores{% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x align-center" style="padding-bottom: 25px;">
        <div class="cell large-12">
            <h2 style="text-align: center;">Lista de <b>autores</b></h2>
        </div>
    </div>


    <div class="grid-x">
        <form method="GET" class="cell grid-x grid-margin-x">{% csrf_token %}
            <div class="cell large-4">
                <input type="text" placeholder="Buscar Autor">
            </div>
            <div class="cell large-2">
                <button type="submit" id="kword" name="kword" class="primay button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200" style="text-align: center;">Nombre</th>
                        <th width="200" style="text-align: center;">Apellidos</th>
                        <th width="200" style="text-align: center;">Nombre Completo</th>
                        <th width="100" style="text-align: center;">Acción</th>

                    </tr>
                </thead>
                <tbody style=" font-size: 12px;">
                    {% for a in autor %}
                    <tr>
                        <td>{{ a.nombre }}</td>
                        <td style="text-align: center;">{{ a.apellidos }}</td>
                        <td style="text-align: center;">{{ a.nombre }} {{ a.apellidos }}</td>
                        <td style="text-align: center;">
                            <a class="button success tiny" href="{% url 'autor_app:detalles' a.id %}">V</a>
                            <a class="button warning tiny" href="{% url 'autor_app:edit' a.id %}">M</a>
                            <a class="button alert tiny" href="{% url 'autor_app:delete' a.id %}">E</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">
                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{ page_obj.previous_page_number }}" aria-label="Anterior">
                                Anterior
                            </a>
                        </li>
                    {% endif %}

                    {% for pag in paginator.page_range %}
                        
                        {% if pag == page_obj.number %}
                            <li class="current">
                                <span class="show-for-sr">Estás en la pag.</span>{{ pag }}
                            </li>
                        {% else %}
                            <li>
                                <a href="?page={{ pag }}" aria-label="Pag. {{ pag }}">{{ pag }}</a>
                            </li>                            
                        {% endif %}

                    {% endfor%}

                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}" aria-label="Siguiente">
                                Siguiente
                            </a>
                        </li>
                    {% endif %}

                </ul>
            </nav>
            {% endif %}
        </div>
    </div>


</div>

{% endblock content %}

biblioteca/templates/autor/ver_autor.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyBiblio - Autor "{{ autor.nombre }} {{ autor.apellidos }}"{% endblock title %}
{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x align-center" style="padding-bottom: 25px;">
            <div class="cell large-12">
                <h2 style="text-align: center;">{{ autor.nombre }} {{ autor.apellidos }}</h2>
            </div>
        </div>

        <div class="grid-x align-center">
            <div class="cell large-4 align-self-middle large-offset-2">
                <img class="max-width: 350px; height: auto;" src="{% static 'img/autor_no_photo.jpg' %}">
            </div>
            <div class="grid-x cell large-6 grid-margin-x align-self-middle" style="height: 80px;">
                <div class="cell large-4" style="text-align: right; font-weight:bolder;">
                    Nombre:
                </div>
                <div class="cell large-8 textocamposrigth">
                    {{ autor.nombre}}
                </div>
                <div class="cell large-4" style="text-align: right; font-weight:bolder;">
                    Apellidos: 
                </div>
                <div class="cell large-8">
                    {{ autor.apellidos}}
                </div>
            </div>
        </div>

        <div class="grid-x align-center">
            <div class="cell large-1">
                <p style="text-align:right; padding-top: 25px;">
                    <button class="button secondary align-center" lass="button secondary clear" onclick="history.back()">Volver</button>
                </p>
            </div>
        </div>

    </div>
{% endblock content %}